#!/bin/bash
cd "$(dirname $0)"/..
if [ -f ./venv/bin/activate ]; then
	source ./venv/bin/activate
else
	python3 -m venv ./venv
	source ./venv/bin/activate
	pip3 install -r requirements.txt
fi
python3 main.py
